### ISSUE TITLE
add token auth

### ISSUE THREAD

**Issue by grillazz** [EnviroMonitor/EnviroMonitorWeb#11]
Hi @zen - please let me know which standard you would like to add to project. 
http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication or http://www.django-rest-framework.org/api-guide/authentication/#json-web-token-authentication ?

**Comment by zen** [comment]
Not really sure.
Are both of them possible to be generated from django admin?

**Comment by lechup** [comment]
@grillazz @zen @ajakubo1 

I think we need to discuss how do we authenticate sensors (or we don't? @zen ) that will post data.

My first idea:
* web (air-monitor.org): readonly access for unauth users (with some reasonable limits?)
* sensors: when user register on air-monitor.org he would receive token that he need to provide into his sensor to be able to POST data on air-monitor.org (for each sensor one token) - write access (with some extended limits?)
* apps: when user register on air-monitor.org he can receive app token - read access (with some reasonable limits?)

**Comment by zen** [comment]
Most urgent for now is to give possibility to post sensor data. I would even assume that you cannot read data if you don't provide data, so only sensor owners should be able to have API read rights. It would mean one token for both might be sufficient.
I agree that token should be generated when you register sensor. Obviously, it can lead to fake sensors :(

**Comment by grillazz** [comment]
I will be voting for JSON Web Token Authentication. "...Unlike the built-in TokenAuthentication scheme, JWT Authentication doesn't need to use a database to validate a token..."

**Comment by zen** [comment]
+1

**Comment by khasinski** [comment]
👍
