### ISSUE TITLE
Remove redundant EnviroMonitorWeb folder in repo root

### ISSUE THREAD

**Issue by lechup** [EnviroMonitor/EnviroMonitorWeb#14]
I think one EnviroMonitorWeb folder is not needed. What do You think @grillazz ?

**Comment by grillazz** [comment]
@lechup this is how I working with Django. So for me it is not duplicate but project skeleton.

**Comment by lechup** [comment]
Hm... Are You sure?

I want to move all files FROM here: 

https://github.com/EnviroMonitor/EnviroMonitorWeb/tree/master/EnviroMonitorWeb

TO:

https://github.com/EnviroMonitor/EnviroMonitorWeb

You will get one directory called **EnviroMonitorWeb** while doing `git clone`.

I don't want to change project app folder and any skeleton there...

**Comment by grillazz** [comment]
So you want to put `manage.py` in repository root together with i.e. `.gitignore` ?

**Comment by lechup** [comment]
Basically yes. There is any reason why not? Dot files are hidden file by default on linux.

Maybe others have different opinion? @ajakubo1 @devnook ?

**Comment by lechup** [comment]
In #23 I've moved some files. Please say what do You think @grillazz

**Comment by lechup** [comment]
Closed by #23 .
