### ISSUE TITLE
redundant views

### ISSUE THREAD

**Issue by grillazz** [EnviroMonitor/EnviroMonitorWeb#16]
Hi All, 

Once we have DRF in place with all the formats: JSON, XML API, ADMIN do we still need redundant views (templates, forms etc) here https://github.com/EnviroMonitor/EnviroMonitorWeb/blob/master/EnviroMonitorWeb/api/views.py ?

Thanks,

Jakub

**Comment by lechup** [comment]
@grillazz :+1: 

Yeah, they are redundant - I think we should stick to ViewSets and remove other manually created views.

PS: What do You think about moving all viewsets classes to `.viewsets ` or `.views` in `api` app?

**Comment by grillazz** [comment]
@lechup i fine with that. @zen are you ok to remove redundant view from project ?

**Comment by zen** [comment]
I guess so

**Comment by grillazz** [comment]
Thanks - I will do that after New Year.
