### ISSUE TITLE
Use model factories from factory_boy

### ISSUE THREAD

**Issue by lechup** [EnviroMonitor/EnviroMonitorWeb#17]
What do You all think about using [factory_boy](https://factoryboy.readthedocs.io/en/latest/) instead of functions like [that](https://github.com/EnviroMonitor/EnviroMonitorWeb/blob/master/EnviroMonitorWeb/api/tests.py#L10)?

**Comment by grillazz** [comment]
Im ok with `factories`

**Comment by lechup** [comment]
@grillazz Cool, I'll add this one this week!

**Comment by grillazz** [comment]
@lechup I will leave uni tests for rest api with you then ?

**Comment by grillazz** [comment]
@lechup one more >> for DRF i suggest to use what is in bundle. You have there `APIRequestFactory` and `RequestFactory` http://www.django-rest-framework.org/api-guide/testing/

**Comment by lechup** [comment]
In #38 I've cleaned up factories a bit. I hope it will also close this one.

**Comment by lechup** [comment]
Closed by #38
