### ISSUE TITLE
expand rest api with django-filters

### ISSUE THREAD

**Issue by grillazz** [EnviroMonitor/EnviroMonitorWeb#4]

**Comment by grillazz** [comment]
@zen could you spec which fields you like to have in filters per model ? example usage https://django-filter.readthedocs.io/en/latest/guide/usage.html

**Comment by zen** [comment]
If i understand correctly, this is only for filtering API output. If so, following will be sufficient for now:
Station: name, test, country, state, county, community, owner, project
Metering: created, station
Project: name
