### ISSUE TITLE
Change add-metering URL

### ISSUE THREAD

**Issue by khasinski** [EnviroMonitor/EnviroMonitorWeb#60]
`POST /api/v1/station/{token}` (:warning: not `station id` since `id` can't change)

**Comment by lechup** [comment]
Hm...

`POST /api/v1/station/{token}`
or
`POST /api/v1/station/add-metering/{token}`

?

**Comment by khasinski** [comment]
I prefer not to have verbs in URL, since we already have `POST` as a verb.

How about 
`POST /api/v1/metering`
with token in JSON body?

**Comment by lechup** [comment]
Make sense. :+1:

**Comment by lechup** [comment]
Should be closed by #62
